/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.ImageIcon;

/**
 *
 * @author admin
 */
public class GiaoDienChinh_JFrame extends javax.swing.JFrame {

    private QuanLyBan_JPanel btn_tool_quanLyBan;
    private QuanLyDoUong_JPanel btn_tool_quanLyDoUong;

    /**
     * Creates new form GiaoDienChinh_JFrame
     */
    public GiaoDienChinh_JFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Trang chủ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btn_quanLyDoUong = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btn_quanLyBan = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jButton4 = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        btn_dangXuat = new javax.swing.JButton();
        tabp_giaoDienChinh = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnu_thoat = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menu_gioiThieu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-restaurant-menu-50.png"))); // NOI18N
        jButton1.setText("Quản lý đặt bàn");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);
        jToolBar1.add(jSeparator6);

        btn_quanLyDoUong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-coffee-to-go-50.png"))); // NOI18N
        btn_quanLyDoUong.setText("Quản lý đồ uống");
        btn_quanLyDoUong.setFocusable(false);
        btn_quanLyDoUong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_quanLyDoUong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_quanLyDoUong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanLyDoUongActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_quanLyDoUong);
        jToolBar1.add(jSeparator7);

        btn_quanLyBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-table-50.png"))); // NOI18N
        btn_quanLyBan.setText("Quản lý bàn");
        btn_quanLyBan.setFocusable(false);
        btn_quanLyBan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_quanLyBan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_quanLyBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanLyBanActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_quanLyBan);
        jToolBar1.add(jSeparator8);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-user-50.png"))); // NOI18N
        jButton4.setText("Quản lý nhân viên");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton4);
        jToolBar1.add(jSeparator9);

        btn_dangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout-icon-48.png"))); // NOI18N
        btn_dangXuat.setText("Đăng xuất");
        btn_dangXuat.setFocusable(false);
        btn_dangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_dangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_dangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangXuatActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_dangXuat);

        jMenu1.setText("Hệ thống");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout-icon-16.png"))); // NOI18N
        jMenuItem1.setText("Đăng xuất");
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        mnu_thoat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnu_thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-edit-delete-icon-16.png"))); // NOI18N
        mnu_thoat.setText("Thoát");
        mnu_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_thoatActionPerformed(evt);
            }
        });
        jMenu1.add(mnu_thoat);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/open-file-icon-16.png"))); // NOI18N
        jMenuItem3.setText("Quản lý đặt bàn");
        jMenu2.add(jMenuItem3);
        jMenu2.add(jSeparator2);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/open-file-icon-16.png"))); // NOI18N
        jMenuItem4.setText("Quản lý bàn");
        jMenu2.add(jMenuItem4);
        jMenu2.add(jSeparator4);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/open-file-icon-16.png"))); // NOI18N
        jMenuItem7.setText("Quản lý đồ uống");
        jMenu2.add(jMenuItem7);
        jMenu2.add(jSeparator5);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-document-edit-icon-16.png"))); // NOI18N
        jMenuItem8.setText("Thống kê");
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Trợ giúp");

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-help-about-icon-16.png"))); // NOI18N
        jMenuItem5.setText("Nội dung");
        jMenu3.add(jMenuItem5);
        jMenu3.add(jSeparator3);

        menu_gioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Help-icon-16.png"))); // NOI18N
        menu_gioiThieu.setText("Giới thiệu");
        menu_gioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_gioiThieuActionPerformed(evt);
            }
        });
        jMenu3.add(menu_gioiThieu);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
                    .addComponent(tabp_giaoDienChinh))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabp_giaoDienChinh, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnu_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_thoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnu_thoatActionPerformed

    /*
        Ngày 21/09/2022 ghi chú bước 7.
        Xử lý sự kiện nhấn nút "Quản lý bàn" thì hiển thị giao diện quản lý bàn ở jtabbed pane
        Dùng if để chỉ tạo 1 lần tránh lặp lại khi click nhiều lần
     */
    private void btn_quanLyBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quanLyBanActionPerformed
        if (btn_tool_quanLyBan == null) {
            btn_tool_quanLyBan = new QuanLyBan_JPanel();
            tabp_giaoDienChinh.addTab("Quản lý bàn", btn_tool_quanLyBan);
        }
        tabp_giaoDienChinh.setSelectedComponent(btn_tool_quanLyBan);
    }//GEN-LAST:event_btn_quanLyBanActionPerformed

    /*
        Ngày 21/09/2022 ghi chú bước 8.
        Xử lý sự kiện nhấn nút "Quản lý đồ uống" thì hiển thị giao diện quản lý bàn ở jtabbed pane
        Dùng if để chỉ tạo 1 lần tránh lặp lại khi click nhiều lần
     */
    private void btn_quanLyDoUongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quanLyDoUongActionPerformed
        if (btn_tool_quanLyDoUong == null) {
            btn_tool_quanLyDoUong = new QuanLyDoUong_JPanel();
            tabp_giaoDienChinh.addTab("Quản lý đồ uống", btn_tool_quanLyDoUong);
        }
        tabp_giaoDienChinh.setSelectedComponent(btn_tool_quanLyDoUong);
    }//GEN-LAST:event_btn_quanLyDoUongActionPerformed

    private void menu_gioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_gioiThieuActionPerformed
        GioiThieu_Dialog gtd = new GioiThieu_Dialog(this, true);
        gtd.setVisible(true);
    }//GEN-LAST:event_menu_gioiThieuActionPerformed

    public DangNhap_Dialog dangnhap;

    private void btn_dangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangXuatActionPerformed
        dangnhap.getTxt_matKhau().setText("");
        if (dangnhap == null) {
            dangnhap = new DangNhap_Dialog(this, true);

        }
        this.setVisible(false);
        dangnhap.setVisible(true);
    }//GEN-LAST:event_btn_dangXuatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienChinh_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dangXuat;
    private javax.swing.JButton btn_quanLyBan;
    private javax.swing.JButton btn_quanLyDoUong;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem menu_gioiThieu;
    private javax.swing.JMenuItem mnu_thoat;
    private javax.swing.JTabbedPane tabp_giaoDienChinh;
    // End of variables declaration//GEN-END:variables
}
